apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-skills-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-skills-artifacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
