apiVersion: v1
kind: Service
metadata:
  name: open-skills
  labels:
    app: open-skills
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: open-skills
